  -- Smart Lib complete database schema
  -- Run this file once in a new Supabase project's SQL Editor.
  -- Create the first account in the app, then promote it to admin using the SQL at the end.

  create extension if not exists pg_trgm;
  create extension if not exists "uuid-ossp";

  create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    full_name text,
    role text not null default 'student' check (role in ('student', 'admin')),
    created_at timestamptz not null default now()
  );

  grant select, insert, update on public.profiles to authenticated;

  alter table public.profiles add column if not exists points_balance integer not null default 0;
  alter table public.profiles drop constraint if exists profiles_points_balance_check;
  alter table public.profiles add constraint profiles_points_balance_check check (points_balance >= 0);

  create table if not exists public.books (
    id bigint generated by default as identity primary key,
    title text not null,
    author text not null,
    category text not null,
    isbn text,
    description text,
    pdf_url text,
    -- Legacy compatibility fields. Digital loan eligibility must not use these values.
    total_copies integer not null default 1 check (total_copies >= 0),
    available_copies integer not null default 1 check (available_copies >= 0),
    search_vector tsvector,
    access_points integer not null default 0,
    page_count integer check (page_count is null or page_count > 0),
    created_at timestamptz not null default now(),
    check (available_copies <= total_copies)
  );

  alter table public.books add column if not exists access_points integer not null default 0;
  alter table public.books add column if not exists page_count integer;
  alter table public.books drop constraint if exists books_page_count_check;
  alter table public.books add constraint books_page_count_check check (page_count is null or page_count > 0);
  alter table public.books drop constraint if exists books_access_points_check;
  alter table public.books add constraint books_access_points_check check (access_points >= 0);

  create table if not exists public.borrow_requests (
    id bigint generated by default as identity primary key,
    student_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'returned', 'revoked')),
    request_date timestamptz not null default now(),
    due_date timestamptz,
    returned_date timestamptz,
    duration_days integer not null default 14 check (duration_days between 7 and 90),
    renewal_count integer not null default 0 check (renewal_count >= 0),
    notes text,
    created_at timestamptz not null default now()
  );

  -- Digital access options include short study sessions (1 and 3 days).
  -- Keep existing installations aligned with the RPC and student UI.
  alter table public.borrow_requests drop constraint if exists borrow_requests_duration_days_valid;
  alter table public.borrow_requests drop constraint if exists borrow_requests_duration_days_check;
  alter table public.borrow_requests
    add constraint borrow_requests_duration_days_check check (duration_days between 1 and 90);

  alter table public.borrow_requests drop constraint if exists borrow_requests_status_check;
  alter table public.borrow_requests
    add constraint borrow_requests_status_check
    check (status in ('pending', 'approved', 'rejected', 'returned', 'revoked'));
  alter table public.borrow_requests add column if not exists points_cost integer not null default 0;
  alter table public.borrow_requests drop constraint if exists borrow_requests_points_cost_check;
  alter table public.borrow_requests add constraint borrow_requests_points_cost_check check (points_cost >= 0);

  create table if not exists public.point_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    amount integer not null check (amount <> 0),
    transaction_type text not null check (transaction_type in ('contribution_reward', 'access_unlock', 'admin_adjustment')),
    reference_id bigint,
    description text not null,
    created_at timestamptz not null default now()
  );

  create table if not exists public.book_contributions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    title text not null,
    author text not null,
    description text,
    pdf_url text,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    points_awarded integer not null default 0 check (points_awarded >= 0),
    approved_book_id bigint references public.books(id) on delete set null,
    reviewed_by uuid references public.profiles(id) on delete set null,
    reviewed_at timestamptz,
    created_at timestamptz not null default now()
  );

  create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete cascade,
    student_id uuid not null references public.profiles(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    comment text,
    created_at timestamptz not null default now(),
    unique (book_id, student_id)
  );

  create table if not exists public.wishlists (
    id bigint generated by default as identity primary key,
    book_id bigint not null references public.books(id) on delete cascade,
    student_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (book_id, student_id)
  );

  create table if not exists public.study_notes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    page integer,
    text text,
    selection_text text,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  create table if not exists public.highlights (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    page integer not null,
    rects jsonb not null,
    color text not null default 'yellow',
    note_id bigint references public.study_notes(id) on delete set null,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
  );

  create table if not exists public.study_drawings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    page integer not null check (page > 0),
    strokes jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now(),
    unique (user_id, book_id, page)
  );

  create table if not exists public.fines (
    id bigint generated by default as identity primary key,
    borrow_request_id bigint not null unique references public.borrow_requests(id) on delete cascade,
    student_id uuid not null references public.profiles(id) on delete cascade,
    amount numeric(10, 2) not null default 0 check (amount >= 0),
    status text not null default 'unpaid' check (status in ('unpaid', 'paid')),
    created_at timestamptz not null default now(),
    paid_at timestamptz
  );

  create table if not exists public.email_queue (
    id bigint generated by default as identity primary key,
    event_type text not null,
    payload jsonb not null,
    processed boolean not null default false,
    created_at timestamptz not null default now(),
    processed_at timestamptz
  );

  create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    event_type text not null,
    title text not null,
    message text not null,
    reference_id bigint,
    read_at timestamptz,
    created_at timestamptz not null default now()
  );

  create table if not exists public.reading_progress (
    user_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    current_page integer not null default 1 check (current_page > 0),
    total_pages integer check (total_pages is null or total_pages > 0),
    updated_at timestamptz not null default now(),
    primary key (user_id, book_id)
  );

  create table if not exists public.assistant_sessions (
    id uuid primary key default uuid_generate_v4(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    title text not null default 'New research chat',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  create table if not exists public.assistant_messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.assistant_sessions(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    results jsonb not null default '[]'::jsonb,
    loans jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
  );

  create index if not exists idx_books_title_trgm on public.books using gin (title gin_trgm_ops);
  create index if not exists idx_books_search_vector on public.books using gin (search_vector);
  create index if not exists idx_borrow_requests_student_status on public.borrow_requests(student_id, status, due_date);
  create index if not exists idx_borrow_requests_book_status on public.borrow_requests(book_id, status);
  create index if not exists idx_books_category on public.books(category);
  create index if not exists idx_study_notes_user_book on public.study_notes(user_id, book_id, page);
  create index if not exists idx_highlights_user_book on public.highlights(user_id, book_id, page);
  create index if not exists idx_fines_student on public.fines(student_id);
  create index if not exists idx_email_queue_event_type on public.email_queue(event_type);
  create index if not exists idx_notifications_user_created on public.notifications(user_id, created_at desc);
  create index if not exists idx_reading_progress_user_updated on public.reading_progress(user_id, updated_at desc);
  create index if not exists idx_assistant_sessions_user on public.assistant_sessions(user_id, updated_at desc);
  create index if not exists idx_assistant_messages_session on public.assistant_messages(session_id, created_at);
  create index if not exists idx_point_transactions_user on public.point_transactions(user_id, created_at desc);
  create index if not exists idx_book_contributions_status on public.book_contributions(status, created_at desc);
  create index if not exists idx_study_drawings_user_book on public.study_drawings(user_id, book_id, page);

  create or replace function public.sync_book_search_vector()
  returns trigger
  language plpgsql
  as $$
  begin
    new.search_vector := to_tsvector(
      'english',
      coalesce(new.title, '') || ' ' ||
      coalesce(new.author, '') || ' ' ||
      coalesce(new.description, '') || ' ' ||
      coalesce(new.category, '')
    );
    return new;
  end;
  $$;

  drop trigger if exists trg_books_search_vector on public.books;
  create trigger trg_books_search_vector
  before insert or update on public.books
  for each row execute function public.sync_book_search_vector();

  update public.books
  set search_vector = to_tsvector(
    'english',
    coalesce(title, '') || ' ' || coalesce(author, '') || ' ' ||
    coalesce(description, '') || ' ' || coalesce(category, '')
  )
  where search_vector is null;

  create or replace function public.search_books(p_query text, p_limit integer default 10)
  returns table(
    id bigint,
    title text,
    author text,
    category text,
    description text,
    pdf_url text,
    available_copies integer,
    rank double precision
  )
  language sql
  stable
  security invoker
  as $$
    select b.id, b.title, b.author, b.category, b.description, b.pdf_url,
          b.available_copies,
          ts_rank(b.search_vector, plainto_tsquery('english', p_query)) as rank
    from public.books b
    where b.search_vector @@ plainto_tsquery('english', p_query)
    order by rank desc
    limit least(greatest(coalesce(p_limit, 10), 1), 50);
  $$;

  create or replace function public.touch_updated_at()
  returns trigger language plpgsql as $$
  begin
    new.updated_at := now();
    return new;
  end;
  $$;

  drop trigger if exists trg_study_notes_updated_at on public.study_notes;
  create trigger trg_study_notes_updated_at
  before update on public.study_notes
  for each row execute function public.touch_updated_at();

  create or replace function public.enqueue_borrow_request_notifications()
  returns trigger language plpgsql security definer set search_path = public as $$
  begin
    if old.status is distinct from new.status and new.status in ('approved', 'rejected') then
      insert into public.email_queue(event_type, payload)
      values ('borrow_request_status', jsonb_build_object(
        'student_id', new.student_id,
        'book_id', new.book_id,
        'status', new.status,
        'request_id', new.id
      ));
      insert into public.notifications(user_id, event_type, title, message, reference_id)
      values (
        new.student_id,
        'borrow_request_status',
        case when new.status = 'approved' then 'Access approved' else 'Request update' end,
        case when new.status = 'approved' then 'Your digital library request was approved.' else 'Your digital library request was not approved.' end,
        new.id
      );
    end if;
    return new;
  end;
  $$;

  drop trigger if exists trg_enqueue_borrow_request_notifications on public.borrow_requests;
  create trigger trg_enqueue_borrow_request_notifications
  after update on public.borrow_requests
  for each row execute function public.enqueue_borrow_request_notifications();

  create or replace function public.calculate_overdue_fines(daily_rate numeric default 0.5)
  returns void language plpgsql security definer set search_path = public as $$
  declare
    loan record;
    days_overdue integer;
  begin
    for loan in
      select id, student_id, due_date
      from public.borrow_requests
      where status = 'approved' and due_date is not null
        and (returned_date is null or returned_date > due_date)
    loop
      days_overdue := greatest(0, date_part('day', now()::date - loan.due_date::date)::integer);
      if days_overdue > 0 then
        insert into public.fines(borrow_request_id, student_id, amount)
        values (loan.id, loan.student_id, days_overdue * daily_rate)
        on conflict (borrow_request_id) do update
        set amount = excluded.amount, status = 'unpaid', created_at = now();
      end if;
    end loop;
  end;
  $$;

  create or replace function public.request_digital_loan(p_book_id bigint, p_duration_days integer)
  returns public.borrow_requests language plpgsql security definer set search_path = public as $$
  declare
    requested public.borrow_requests;
    required_points integer;
    user_points integer;
    book_points integer;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if p_duration_days < 1 or p_duration_days > 90 then
      raise exception 'Choose a lending period between 1 and 90 days';
    end if;

    select access_points into book_points from public.books where id = p_book_id;
    if book_points is null then raise exception 'Resource not found'; end if;
    required_points := ceil(p_duration_days / 7.0)::integer * book_points;

    perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text || ':' || p_book_id::text, 0));
    if exists (
      select 1 from public.borrow_requests
      where student_id = auth.uid() and book_id = p_book_id
        and (status = 'pending' or (status = 'approved' and returned_date is null and due_date > now()))
    ) then
      raise exception 'You already have an active request or loan for this resource';
    end if;

    select points_balance into user_points from public.profiles where id = auth.uid() for update;
    if user_points is null then raise exception 'Profile not found'; end if;
    if user_points < required_points then
      raise exception 'You need % more points to unlock this resource for % days', required_points - user_points, p_duration_days;
    end if;

    insert into public.borrow_requests(student_id, book_id, duration_days, points_cost)
    values (auth.uid(), p_book_id, p_duration_days, required_points)
    returning * into requested;
    if required_points > 0 then
      update public.profiles set points_balance = points_balance - required_points where id = auth.uid();
      insert into public.point_transactions(user_id, amount, transaction_type, reference_id, description)
      values (auth.uid(), -required_points, 'access_unlock', requested.id, 'Unlocked digital access');
    end if;
    return requested;
  end;
  $$;

  create or replace function public.provision_profile()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
  as $$
  begin
    insert into public.profiles (id, email, role)
    values (new.id, coalesce(new.email, ''), 'student')
    on conflict (id) do update set email = excluded.email;
    return new;
  end;
  $$;

  drop trigger if exists on_auth_user_created on auth.users;
  create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.provision_profile();

  -- Backfill accounts created before this schema was installed.
  insert into public.profiles (id, email, role)
  select id, coalesce(email, ''), 'student'
  from auth.users
  on conflict (id) do update set email = excluded.email;

  create or replace function public.prevent_student_role_change()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
  as $$
  begin
    if auth.uid() is not null
      and not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
      if old.role is distinct from new.role then
        raise exception 'Only an administrator can change account roles';
      end if;
      if old.points_balance is distinct from new.points_balance then
        raise exception 'Only an administrator or approved workflow can change points';
      end if;
      if old.email is distinct from new.email then
        raise exception 'Email changes must be handled by account authentication';
      end if;
    end if;
    return new;
  end;
  $$;

  drop trigger if exists trg_profiles_role_guard on public.profiles;
  create trigger trg_profiles_role_guard
  before update on public.profiles
  for each row execute function public.prevent_student_role_change();

  create or replace function public.is_admin()
  returns boolean
  language sql
  stable
  security definer
  set search_path = public
  as $$
    select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
  $$;

  create or replace function public.submit_book_contribution(
    p_title text,
    p_author text,
    p_description text default null,
    p_pdf_url text default null
  )
  returns public.book_contributions language plpgsql security definer set search_path = public as $$
  declare
    submitted public.book_contributions;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if nullif(trim(p_title), '') is null or nullif(trim(p_author), '') is null then
      raise exception 'Title and author are required';
    end if;
    insert into public.book_contributions(user_id, title, author, description, pdf_url)
    values (auth.uid(), trim(p_title), trim(p_author), nullif(trim(p_description), ''), nullif(trim(p_pdf_url), ''))
    returning * into submitted;
    return submitted;
  end;
  $$;

  create or replace function public.admin_review_book_contribution(
    contribution_id bigint,
    decision text,
    reward_points integer default 25,
    access_points integer default 0
  )
  returns public.book_contributions language plpgsql security definer set search_path = public as $$
  declare
    contribution public.book_contributions;
    created_book_id bigint;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if decision not in ('approved', 'rejected') then raise exception 'Invalid contribution decision'; end if;
    if reward_points < 0 or reward_points > 100 then raise exception 'Reward must be between 0 and 100 points'; end if;
    if access_points < 0 then raise exception 'Access cost cannot be negative'; end if;

    select * into contribution from public.book_contributions where id = contribution_id for update;
    if contribution.id is null or contribution.status <> 'pending' then raise exception 'Pending contribution not found'; end if;

    if decision = 'approved' then
      insert into public.books(title, author, category, description, pdf_url, access_points)
      values (contribution.title, contribution.author, 'Community contribution', contribution.description, contribution.pdf_url, access_points)
      returning id into created_book_id;
      update public.profiles set points_balance = points_balance + reward_points where id = contribution.user_id;
      if reward_points > 0 then
        insert into public.point_transactions(user_id, amount, transaction_type, reference_id, description)
        values (contribution.user_id, reward_points, 'contribution_reward', contribution.id, 'Approved library contribution');
      end if;
    end if;

    update public.book_contributions
    set status = decision,
        points_awarded = case when decision = 'approved' then reward_points else 0 end,
        approved_book_id = created_book_id,
        reviewed_by = auth.uid(),
        reviewed_at = now()
    where id = contribution.id
    returning * into contribution;
    insert into public.notifications(user_id, event_type, title, message, reference_id)
    values (
      contribution.user_id,
      'contribution_review',
      case when decision = 'approved' then 'Contribution approved' else 'Contribution reviewed' end,
      case when decision = 'approved' then 'Your resource was added to the library.' else 'Your submitted resource was not approved.' end,
      contribution.id
    );
    return contribution;
  end;
  $$;

  create or replace function public.admin_set_profile_role(target_user_id uuid, new_role text)
  returns public.profiles language plpgsql security definer set search_path = public as $$
  declare
    updated_profile public.profiles;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if new_role not in ('student', 'admin') then raise exception 'Invalid account role'; end if;
    update public.profiles set role = new_role where id = target_user_id returning * into updated_profile;
    if updated_profile.id is null then raise exception 'Profile not found'; end if;
    return updated_profile;
  end;
  $$;

  create or replace function public.admin_decide_borrow_request(request_id bigint, decision text)
  returns public.borrow_requests language plpgsql security definer set search_path = public as $$
  declare
    updated_request public.borrow_requests;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if decision not in ('approved', 'rejected') then raise exception 'Invalid request decision'; end if;
    update public.borrow_requests
    set status = decision,
        due_date = case when decision = 'approved' then now() + make_interval(days => duration_days) else null end
    where id = request_id and status = 'pending'
    returning * into updated_request;
    if updated_request.id is null then raise exception 'Pending request not found'; end if;
    return updated_request;
  end;
  $$;

  create or replace function public.renew_digital_loan(request_id bigint, extension_days integer default 14)
  returns public.borrow_requests language plpgsql security definer set search_path = public as $$
  declare
    updated_request public.borrow_requests;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if extension_days < 7 or extension_days > 30 then raise exception 'Renewal must be between 7 and 30 days'; end if;
    update public.borrow_requests
    set due_date = greatest(coalesce(due_date, now()), now()) + make_interval(days => extension_days),
        renewal_count = renewal_count + 1
    where id = request_id and student_id = auth.uid() and status = 'approved'
      and returned_date is null and due_date > now() and renewal_count < 2
    returning * into updated_request;
    if updated_request.id is null then raise exception 'Loan cannot be renewed'; end if;
    return updated_request;
  end;
  $$;

  create or replace function public.return_digital_loan(request_id bigint)
  returns public.borrow_requests language plpgsql security definer set search_path = public as $$
  declare
    updated_request public.borrow_requests;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    update public.borrow_requests
    set status = 'returned', returned_date = now()
    where id = request_id and student_id = auth.uid() and status = 'approved' and returned_date is null
    returning * into updated_request;
    if updated_request.id is null then raise exception 'Loan cannot be returned'; end if;
    return updated_request;
  end;
  $$;

  create or replace function public.revoke_digital_loan(request_id bigint)
  returns public.borrow_requests language plpgsql security definer set search_path = public as $$
  declare
    updated_request public.borrow_requests;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    update public.borrow_requests
    set status = 'revoked', returned_date = now()
    where id = request_id and status = 'approved' and returned_date is null
    returning * into updated_request;
    if updated_request.id is null then raise exception 'Approved loan not found or already closed'; end if;
    return updated_request;
  end;
  $$;

  alter table public.profiles enable row level security;
  alter table public.books enable row level security;
  alter table public.borrow_requests enable row level security;
  alter table public.reviews enable row level security;
  alter table public.wishlists enable row level security;
  alter table public.study_notes enable row level security;
  alter table public.highlights enable row level security;
  alter table public.study_drawings enable row level security;
  alter table public.fines enable row level security;
  alter table public.email_queue enable row level security;
  alter table public.point_transactions enable row level security;
  alter table public.book_contributions enable row level security;
  alter table public.assistant_sessions enable row level security;
  alter table public.assistant_messages enable row level security;
  alter table public.notifications enable row level security;
  alter table public.reading_progress enable row level security;

  drop policy if exists profiles_select_self_or_admin on public.profiles;
  create policy profiles_select_self_or_admin on public.profiles
  for select using (id = auth.uid() or public.is_admin());

  drop policy if exists profiles_insert_self on public.profiles;
  create policy profiles_insert_self on public.profiles
  for insert to authenticated
  with check (id = auth.uid() and role = 'student');

  drop policy if exists profiles_update_self on public.profiles;
  create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

  drop policy if exists books_read_authenticated on public.books;
  create policy books_read_authenticated on public.books
  for select to authenticated using (true);

  drop policy if exists books_admin_insert on public.books;
  create policy books_admin_insert on public.books
  for insert to authenticated with check (public.is_admin());

  drop policy if exists books_admin_update on public.books;
  create policy books_admin_update on public.books
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

  drop policy if exists books_admin_delete on public.books;
  create policy books_admin_delete on public.books
  for delete to authenticated using (public.is_admin());

  drop policy if exists borrow_requests_read_owner_or_admin on public.borrow_requests;
  create policy borrow_requests_read_owner_or_admin on public.borrow_requests
  for select to authenticated using (student_id = auth.uid() or public.is_admin());

  drop policy if exists borrow_requests_admin_update on public.borrow_requests;
  create policy borrow_requests_admin_update on public.borrow_requests
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

  drop policy if exists reviews_read_authenticated on public.reviews;
  create policy reviews_read_authenticated on public.reviews
  for select to authenticated using (true);

  drop policy if exists reviews_insert_own on public.reviews;
  create policy reviews_insert_own on public.reviews
  for insert to authenticated with check (student_id = auth.uid());

  drop policy if exists reviews_update_own_or_admin on public.reviews;
  create policy reviews_update_own_or_admin on public.reviews
  for update to authenticated
  using (student_id = auth.uid() or public.is_admin())
  with check (student_id = auth.uid() or public.is_admin());

  drop policy if exists reviews_delete_own_or_admin on public.reviews;
  create policy reviews_delete_own_or_admin on public.reviews
  for delete to authenticated using (student_id = auth.uid() or public.is_admin());

  drop policy if exists wishlists_manage_own_or_admin on public.wishlists;
  create policy wishlists_manage_own_or_admin on public.wishlists
  for all to authenticated
  using (student_id = auth.uid() or public.is_admin())
  with check (student_id = auth.uid() or public.is_admin());

  drop policy if exists study_notes_manage_own_or_admin on public.study_notes;
  create policy study_notes_manage_own_or_admin on public.study_notes
  for all to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

  drop policy if exists highlights_manage_own_or_admin on public.highlights;
  create policy highlights_manage_own_or_admin on public.highlights
  for all to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

  drop policy if exists study_drawings_manage_own_or_admin on public.study_drawings;
  create policy study_drawings_manage_own_or_admin on public.study_drawings
  for all to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

  drop policy if exists fines_read_own_or_admin on public.fines;
  create policy fines_read_own_or_admin on public.fines
  for select to authenticated using (student_id = auth.uid() or public.is_admin());

  drop policy if exists fines_admin_update on public.fines;
  create policy fines_admin_update on public.fines
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

  drop policy if exists assistant_sessions_manage_own on public.assistant_sessions;
  create policy assistant_sessions_manage_own on public.assistant_sessions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

  drop policy if exists assistant_messages_manage_own on public.assistant_messages;
  create policy assistant_messages_manage_own on public.assistant_messages
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

  drop policy if exists point_transactions_read_own_or_admin on public.point_transactions;
  create policy point_transactions_read_own_or_admin on public.point_transactions
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

  drop policy if exists book_contributions_read_own_or_admin on public.book_contributions;
  create policy book_contributions_read_own_or_admin on public.book_contributions
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

  drop policy if exists book_contributions_insert_own on public.book_contributions;
  create policy book_contributions_insert_own on public.book_contributions
  for insert to authenticated with check (user_id = auth.uid() and status = 'pending');

  drop policy if exists notifications_read_own on public.notifications;
  create policy notifications_read_own on public.notifications
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

  drop policy if exists notifications_update_own on public.notifications;
  create policy notifications_update_own on public.notifications
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

  drop policy if exists reading_progress_manage_own on public.reading_progress;
  create policy reading_progress_manage_own on public.reading_progress
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

  grant select, insert, update, delete on public.books to authenticated;
  grant select, update on public.borrow_requests to authenticated;
  grant select, insert, update, delete on public.reviews to authenticated;
  grant select, insert, update, delete on public.wishlists to authenticated;
  grant select, insert, update, delete on public.study_notes to authenticated;
  grant select, insert, update, delete on public.highlights to authenticated;
  grant select, insert, update, delete on public.study_drawings to authenticated;
  grant select, update on public.fines to authenticated;
  grant select on public.point_transactions to authenticated;
  grant select, insert on public.book_contributions to authenticated;
  grant select, update on public.notifications to authenticated;
  grant select, insert, update, delete on public.reading_progress to authenticated;
  grant select, insert, update, delete on public.assistant_sessions to authenticated;
  grant select, insert, update, delete on public.assistant_messages to authenticated;
  grant usage, select on all sequences in schema public to authenticated;
  grant execute on function public.search_books(text, integer) to authenticated;
  grant execute on function public.request_digital_loan(bigint, integer) to authenticated;
  grant execute on function public.submit_book_contribution(text, text, text, text) to authenticated;
  grant execute on function public.admin_review_book_contribution(bigint, text, integer, integer) to authenticated;
  grant execute on function public.admin_set_profile_role(uuid, text) to authenticated;
  grant execute on function public.admin_decide_borrow_request(bigint, text) to authenticated;
  grant execute on function public.renew_digital_loan(bigint, integer) to authenticated;
  grant execute on function public.return_digital_loan(bigint) to authenticated;
  grant execute on function public.revoke_digital_loan(bigint) to authenticated;

  -- Do not grant direct student inserts. Student requests must use the validated RPC.
  revoke insert on public.borrow_requests from anon, authenticated;

  revoke all on public.email_queue from anon, authenticated;
  revoke all on function public.calculate_overdue_fines(numeric) from public;

  -- Storage bucket configuration for e-books
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values (
    'ebooks',
    'ebooks',
    false,
    52428800, -- 50 MB limit
    array['application/pdf']
  )
  on conflict (id) do update set
    public = false,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/pdf'];

  -- These columns are required by the storage policies below. Keep them
  -- available before policy creation for fresh installations.
  alter table public.books add column if not exists storage_provider text not null default 'supabase';
  alter table public.books add column if not exists storage_file_id text;
  alter table public.books add column if not exists storage_path text;
  alter table public.books add column if not exists file_name text;
  alter table public.books add column if not exists file_size bigint;
  alter table public.books add column if not exists mime_type text;
  alter table public.books add column if not exists access_mode text not null default 'loan';
  alter table public.books add column if not exists access_duration_days integer not null default 30;

  drop policy if exists "Admin manage ebooks storage" on storage.objects;
  create policy "Admin manage ebooks storage" on storage.objects
  for all to authenticated
  using (bucket_id = 'ebooks' and public.is_admin())
  with check (bucket_id = 'ebooks' and public.is_admin());

  drop policy if exists "Student read approved loan ebooks" on storage.objects;
  create policy "Student read approved loan ebooks" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'ebooks' and (
      public.is_admin() or
      name like 'contributions/' || auth.uid()::text || '/%' or
      exists (
        select 1 from public.books b
        join public.borrow_requests br on br.book_id = b.id
        where (b.storage_path = name or b.pdf_url = name or b.pdf_url like '%' || name)
          and br.student_id = auth.uid()
          and br.status = 'approved'
          and br.returned_date is null
          and br.due_date > now()
      )
    )
  );

  -- After creating your first account, promote it manually from the SQL editor:
  -- update public.profiles set role = 'admin' where email = 'your-admin-email@example.com';

  -- Compatibility patch for newer features that rely on protected library storage and access grants.
  -- This keeps older installations usable when the admin dashboard and reader pages are enabled.
  alter table public.books add column if not exists storage_provider text not null default 'supabase';
  alter table public.books add column if not exists storage_file_id text;
  alter table public.books add column if not exists storage_path text;
  alter table public.books add column if not exists file_name text;
  alter table public.books add column if not exists file_size bigint;
  alter table public.books add column if not exists mime_type text;
  alter table public.books add column if not exists access_mode text not null default 'loan';
  alter table public.books add column if not exists access_duration_days integer not null default 30;
  alter table public.books drop constraint if exists books_access_duration_days_check;
  alter table public.books add constraint books_access_duration_days_check check (access_duration_days between 1 and 3650);

  alter table public.book_contributions add column if not exists storage_provider text not null default 'supabase';
  alter table public.book_contributions add column if not exists storage_file_id text;
  alter table public.book_contributions add column if not exists storage_path text;
  alter table public.book_contributions add column if not exists file_name text;
  alter table public.book_contributions add column if not exists file_size bigint;
  alter table public.book_contributions add column if not exists mime_type text;
  alter table public.book_contributions add column if not exists review_feedback text;

  alter table public.book_contributions drop constraint if exists book_contributions_status_check;
  alter table public.book_contributions add constraint book_contributions_status_check
    check (status in ('pending', 'approved', 'rejected', 'revision_requested', 'withdrawn'));

  alter table public.books drop constraint if exists books_storage_provider_check;
  alter table public.books add constraint books_storage_provider_check
    check (storage_provider in ('supabase', 'google_drive', 'external'));
  alter table public.book_contributions drop constraint if exists book_contributions_storage_provider_check;
  alter table public.book_contributions add constraint book_contributions_storage_provider_check
    check (storage_provider in ('supabase', 'google_drive', 'external'));

  create table if not exists public.recognition_awards (
    id bigint generated by default as identity primary key,
    student_id uuid not null references public.profiles(id) on delete cascade,
    category text not null,
    points integer not null check (points > 0),
    reason text not null,
    awarded_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
  );

  create table if not exists public.book_access_grants (
    id bigint generated by default as identity primary key,
    student_id uuid not null references public.profiles(id) on delete cascade,
    book_id bigint not null references public.books(id) on delete cascade,
    access_type text not null default 'admin_grant',
    points_paid integer not null default 0 check (points_paid >= 0),
    granted_at timestamptz not null default now(),
    expires_at timestamptz,
    status text not null default 'active' check (status in ('active', 'expired', 'revoked')),
    reason text,
    created_at timestamptz not null default now()
  );

  create table if not exists public.rewards (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    points_cost integer not null check (points_cost > 0),
    reward_type text not null default 'academic',
    stock integer check (stock is null or stock >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
  );

  create table if not exists public.achievements (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text not null,
    created_at timestamptz not null default now()
  );

  create table if not exists public.user_achievements (
    user_id uuid not null references public.profiles(id) on delete cascade,
    achievement_id bigint not null references public.achievements(id) on delete cascade,
    awarded_at timestamptz not null default now(),
    primary key (user_id, achievement_id)
  );

  create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    actor_id uuid references public.profiles(id) on delete set null,
    action text not null,
    target_type text not null,
    target_id bigint,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
  );

  alter table public.recognition_awards enable row level security;
  alter table public.book_access_grants enable row level security;
  alter table public.rewards enable row level security;
  alter table public.achievements enable row level security;
  alter table public.user_achievements enable row level security;
  alter table public.audit_logs enable row level security;

  drop policy if exists recognition_awards_read_own_or_admin on public.recognition_awards;
  create policy recognition_awards_read_own_or_admin on public.recognition_awards
  for select to authenticated using (student_id = auth.uid() or public.is_admin());

  drop policy if exists book_access_grants_read_own_or_admin on public.book_access_grants;
  create policy book_access_grants_read_own_or_admin on public.book_access_grants
  for select to authenticated using (student_id = auth.uid() or public.is_admin());

  drop policy if exists rewards_read_authenticated on public.rewards;
  create policy rewards_read_authenticated on public.rewards
  for select to authenticated using (is_active or public.is_admin());

  drop policy if exists achievements_read_authenticated on public.achievements;
  create policy achievements_read_authenticated on public.achievements
  for select to authenticated using (true);

  drop policy if exists user_achievements_read_own_or_admin on public.user_achievements;
  create policy user_achievements_read_own_or_admin on public.user_achievements
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

  drop policy if exists audit_logs_read_admin on public.audit_logs;
  create policy audit_logs_read_admin on public.audit_logs
  for select to authenticated using (public.is_admin());

  grant select on public.recognition_awards, public.book_access_grants, public.rewards,
    public.achievements, public.user_achievements to authenticated;
  grant select on public.audit_logs to authenticated;

  create or replace function public.submit_book_contribution_v2(
    p_title text,
    p_author text,
    p_description text default null,
    p_pdf_url text default null,
    p_storage_provider text default 'supabase',
    p_storage_file_id text default null,
    p_storage_path text default null,
    p_file_name text default null,
    p_file_size bigint default null,
    p_mime_type text default null
  )
  returns public.book_contributions
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    submitted public.book_contributions;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if nullif(trim(p_title), '') is null or nullif(trim(p_author), '') is null then
      raise exception 'Title and author are required';
    end if;
    if p_storage_provider not in ('supabase', 'google_drive', 'external') then
      raise exception 'Invalid storage provider';
    end if;
    if p_file_size is not null and (p_file_size < 0 or p_file_size > 52428800) then
      raise exception 'PDF files must be 50 MB or smaller';
    end if;

    insert into public.book_contributions(
      user_id, title, author, description, pdf_url,
      storage_provider, storage_file_id, storage_path, file_name, file_size, mime_type
    ) values (
      auth.uid(), trim(p_title), trim(p_author), nullif(trim(p_description), ''), nullif(trim(p_pdf_url), ''),
      p_storage_provider, nullif(trim(p_storage_file_id), ''), nullif(trim(p_storage_path), ''),
      nullif(trim(p_file_name), ''), p_file_size, nullif(trim(p_mime_type), '')
    ) returning * into submitted;
    return submitted;
  end;
  $$;

  create or replace function public.student_resubmit_contribution_v2(
    contribution_id bigint,
    contribution_title text,
    contribution_author text,
    contribution_description text default null,
    contribution_pdf_url text default null,
    contribution_storage_provider text default 'supabase',
    contribution_storage_file_id text default null,
    contribution_storage_path text default null,
    contribution_file_name text default null,
    contribution_file_size bigint default null,
    contribution_mime_type text default null
  )
  returns public.book_contributions
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    updated_contribution public.book_contributions;
  begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if nullif(trim(contribution_title), '') is null or nullif(trim(contribution_author), '') is null then
      raise exception 'Title and author are required';
    end if;
    update public.book_contributions
    set title = trim(contribution_title),
        author = trim(contribution_author),
        description = nullif(trim(contribution_description), ''),
        pdf_url = nullif(trim(contribution_pdf_url), ''),
        storage_provider = contribution_storage_provider,
        storage_file_id = nullif(trim(contribution_storage_file_id), ''),
        storage_path = nullif(trim(contribution_storage_path), ''),
        file_name = nullif(trim(contribution_file_name), ''),
        file_size = contribution_file_size,
        mime_type = nullif(trim(contribution_mime_type), ''),
        status = 'pending',
        review_feedback = null,
        reviewed_by = null,
        reviewed_at = null
    where id = contribution_id and user_id = auth.uid() and status = 'revision_requested'
    returning * into updated_contribution;
    if updated_contribution.id is null then raise exception 'Contribution is not available for revision'; end if;
    return updated_contribution;
  end;
  $$;

  create or replace function public.admin_request_contribution_revision(contribution_id bigint, feedback text)
  returns public.book_contributions
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare updated_contribution public.book_contributions;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if nullif(trim(feedback), '') is null then raise exception 'Revision feedback is required'; end if;
    update public.book_contributions
    set status = 'revision_requested', review_feedback = trim(feedback), reviewed_by = auth.uid(), reviewed_at = now()
    where id = contribution_id and status = 'pending'
    returning * into updated_contribution;
    if updated_contribution.id is null then raise exception 'Pending contribution not found'; end if;
    insert into public.notifications(user_id, event_type, title, message, reference_id)
    values (updated_contribution.user_id, 'contribution_revision', 'Revision requested', trim(feedback), contribution_id);
    return updated_contribution;
  end;
  $$;

  create or replace function public.admin_award_recognition(
    target_user_id uuid,
    award_category text,
    award_points integer,
    award_reason text
  )
  returns public.recognition_awards
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    new_award public.recognition_awards;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if award_points <= 0 then raise exception 'Award points must be positive'; end if;
    if nullif(trim(award_reason), '') is null then raise exception 'Award reason is required'; end if;
    insert into public.recognition_awards(student_id, category, points, reason, awarded_by)
    values (target_user_id, award_category, award_points, trim(award_reason), auth.uid())
    returning * into new_award;
    update public.profiles set points_balance = points_balance + award_points where id = target_user_id;
    insert into public.point_transactions(user_id, amount, transaction_type, reference_id, description)
    values (target_user_id, award_points, 'admin_adjustment', new_award.id, 'Recognition award: ' || trim(award_category));
    return new_award;
  end;
  $$;

  create or replace function public.admin_grant_book_access(
    target_user_id uuid,
    target_book_id bigint,
    duration_days integer default 7,
    grant_reason text default null
  )
  returns public.book_access_grants
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    created_grant public.book_access_grants;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if duration_days < 1 or duration_days > 3650 then raise exception 'Access duration must be between 1 and 3650 days'; end if;
    insert into public.book_access_grants(student_id, book_id, access_type, expires_at, status, reason)
    values (target_user_id, target_book_id, 'admin_grant', now() + make_interval(days => duration_days), 'active', coalesce(grant_reason, 'Administrative access grant'))
    returning * into created_grant;
    return created_grant;
  end;
  $$;

  create or replace function public.admin_revoke_book_access(grant_id bigint, revoke_reason text default 'Administrator revoked access')
  returns public.book_access_grants
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    updated_grant public.book_access_grants;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    update public.book_access_grants
    set status = 'revoked', reason = coalesce(revoke_reason, 'Administrator revoked access')
    where id = grant_id
    returning * into updated_grant;
    if updated_grant.id is null then raise exception 'Access grant not found'; end if;
    return updated_grant;
  end;
  $$;

  create or replace function public.admin_create_reward(
    reward_name text,
    reward_description text default null,
    reward_cost integer default 50,
    reward_kind text default 'profile_badge',
    reward_stock integer default null
  )
  returns public.rewards
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    created_reward public.rewards;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    if nullif(trim(reward_name), '') is null then raise exception 'Reward name is required'; end if;
    if reward_cost <= 0 then raise exception 'Reward cost must be positive'; end if;
    insert into public.rewards(name, description, points_cost, reward_type, stock, is_active)
    values (trim(reward_name), nullif(trim(reward_description), ''), reward_cost, coalesce(reward_kind, 'profile_badge'), reward_stock, true)
    returning * into created_reward;
    return created_reward;
  end;
  $$;

  create or replace function public.admin_set_reward_active(reward_id bigint, active boolean)
  returns public.rewards
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    updated_reward public.rewards;
  begin
    if not public.is_admin() then raise exception 'Administrator access required'; end if;
    update public.rewards set is_active = active where id = reward_id returning * into updated_reward;
    if updated_reward.id is null then raise exception 'Reward not found'; end if;
    return updated_reward;
  end;
  $$;

  grant execute on function public.submit_book_contribution_v2(text, text, text, text, text, text, text, text, bigint, text) to authenticated;
  grant execute on function public.student_resubmit_contribution_v2(bigint, text, text, text, text, text, text, text, text, bigint, text) to authenticated;
  grant execute on function public.admin_review_book_contribution(bigint, text, integer, integer) to authenticated;
  grant execute on function public.admin_request_contribution_revision(bigint, text) to authenticated;
  grant execute on function public.admin_award_recognition(uuid, text, integer, text) to authenticated;
  grant execute on function public.admin_grant_book_access(uuid, bigint, integer, text) to authenticated;
  grant execute on function public.admin_revoke_book_access(bigint, text) to authenticated;
  grant execute on function public.admin_create_reward(text, text, integer, text, integer) to authenticated;
  grant execute on function public.admin_set_reward_active(bigint, boolean) to authenticated;

  -- Ensure storage policy allows the protected ebook workflow used by the app.
  drop policy if exists "Students upload contribution PDFs" on storage.objects;
  create policy "Students upload contribution PDFs" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'ebooks'
    and name like 'contributions/' || auth.uid()::text || '/%'
  );

  drop policy if exists "Owners and admins read contribution PDFs" on storage.objects;
  create policy "Owners and admins read contribution PDFs" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'ebooks'
    and (
      public.is_admin()
      or name like 'contributions/' || auth.uid()::text || '/%'
      or exists (
        select 1 from public.books b
        join public.borrow_requests br on br.book_id = b.id
        where (b.storage_path = name or b.pdf_url = name or b.pdf_url like '%' || name)
          and br.student_id = auth.uid()
          and br.status = 'approved'
          and br.returned_date is null
          and br.due_date > now()
      )
      or exists (
        select 1 from public.books b
        join public.book_access_grants bag on bag.book_id = b.id
        where (b.storage_path = name or b.pdf_url = name or b.pdf_url like '%' || name)
          and bag.student_id = auth.uid()
          and bag.status = 'active'
          and bag.expires_at > now()
      )
    )
  );

  -- This block intentionally avoids using direct table-level inserts for student uploads.
  revoke insert on public.book_contributions from anon, authenticated;

  -- Add optional service table indexes to keep admin analytics responsive.
  create index if not exists idx_book_access_grants_student_status on public.book_access_grants(student_id, status, expires_at);
  create index if not exists idx_book_access_grants_book_status on public.book_access_grants(book_id, status);
  create index if not exists idx_rewards_active on public.rewards(is_active, reward_type);
  create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);
  create index if not exists idx_recognition_awards_student on public.recognition_awards(student_id, created_at desc);

  -- The older schema may not have these columns yet; this compatibility step keeps reads/writes consistent.
  alter table public.books add column if not exists storage_provider text not null default 'supabase';
  alter table public.books add column if not exists storage_file_id text;
  alter table public.books add column if not exists storage_path text;
  alter table public.books add column if not exists file_name text;
  alter table public.books add column if not exists file_size bigint;
  alter table public.books add column if not exists mime_type text;
  alter table public.books add column if not exists access_mode text not null default 'loan';
  alter table public.books add column if not exists access_duration_days integer not null default 30;
