-- E-Smart Library baseline schema
-- Run this once in a new Supabase project's SQL Editor before the files in supabase/migrations.
-- Digital lending is enforced by request_digital_loan() and does not depend on copy counts.

create extension if not exists pg_trgm;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  isbn text,
  description text,
  pdf_url text,
  -- Legacy compatibility fields. Digital loan eligibility must not use these values.
  total_copies integer not null default 1 check (total_copies >= 0),
  available_copies integer not null default 1 check (available_copies >= 0),
  search_vector tsvector,
  created_at timestamptz not null default now(),
  check (available_copies <= total_copies)
);

create table if not exists public.borrow_requests (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'returned')),
  request_date timestamptz not null default now(),
  due_date timestamptz,
  returned_date timestamptz,
  renewal_count integer not null default 0 check (renewal_count >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_books_title_trgm on public.books using gin (title gin_trgm_ops);
create index if not exists idx_books_search_vector on public.books using gin (search_vector);
create index if not exists idx_borrow_requests_student_status on public.borrow_requests(student_id, status, due_date);
create index if not exists idx_borrow_requests_book_status on public.borrow_requests(book_id, status);

create or replace function public.sync_book_search_vector()
returns trigger
language plpgsql
as $$
begin
  new.search_vector := to_tsvector(
    'english',
    coalesce(new.title, '') || ' ' ||
    coalesce(new.author, '') || ' ' ||
    coalesce(new.description, '') || ' ' ||
    coalesce(new.category, '')
  );
  return new;
end;
$$;

drop trigger if exists trg_books_search_vector on public.books;
create trigger trg_books_search_vector
before insert or update on public.books
for each row execute function public.sync_book_search_vector();

update public.books
set search_vector = to_tsvector(
  'english',
  coalesce(title, '') || ' ' || coalesce(author, '') || ' ' ||
  coalesce(description, '') || ' ' || coalesce(category, '')
)
where search_vector is null;

create or replace function public.search_books(p_query text, p_limit integer default 10)
returns table(
  id bigint,
  title text,
  author text,
  category text,
  description text,
  pdf_url text,
  available_copies integer,
  rank double precision
)
language sql
stable
security invoker
as $$
  select b.id, b.title, b.author, b.category, b.description, b.pdf_url,
         b.available_copies,
         ts_rank(b.search_vector, plainto_tsquery('english', p_query)) as rank
  from public.books b
  where b.search_vector @@ plainto_tsquery('english', p_query)
  order by rank desc
  limit least(greatest(coalesce(p_limit, 10), 1), 50);
$$;

create or replace function public.provision_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'student')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.provision_profile();

create or replace function public.prevent_student_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.role is distinct from new.role
     and not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    raise exception 'Only an administrator can change account roles';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_role_guard on public.profiles;
create trigger trg_profiles_role_guard
before update on public.profiles
for each row execute function public.prevent_student_role_change();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.borrow_requests enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles
for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists books_read_authenticated on public.books;
create policy books_read_authenticated on public.books
for select to authenticated using (true);

drop policy if exists books_admin_insert on public.books;
create policy books_admin_insert on public.books
for insert to authenticated with check (public.is_admin());

drop policy if exists books_admin_update on public.books;
create policy books_admin_update on public.books
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists books_admin_delete on public.books;
create policy books_admin_delete on public.books
for delete to authenticated using (public.is_admin());

drop policy if exists borrow_requests_read_owner_or_admin on public.borrow_requests;
create policy borrow_requests_read_owner_or_admin on public.borrow_requests
for select to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists borrow_requests_admin_update on public.borrow_requests;
create policy borrow_requests_admin_update on public.borrow_requests
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Do not grant direct student inserts. Student requests must use the validated RPC
-- in 20260908_add_digital_lending.sql.
revoke insert on public.borrow_requests from anon, authenticated;

-- After creating your first account, promote it manually from the SQL editor:
-- update public.profiles set role = 'admin' where email = 'your-admin-email@example.com';
