-- Smart Lib complete database schema
-- Run this file once in a new Supabase project's SQL Editor.
-- Create the first account in the app, then promote it to admin using the SQL at the end.

create extension if not exists pg_trgm;
create extension if not exists "uuid-ossp";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

grant select, insert, update on public.profiles to authenticated;

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  isbn text,
  description text,
  pdf_url text,
  -- Legacy compatibility fields. Digital loan eligibility must not use these values.
  total_copies integer not null default 1 check (total_copies >= 0),
  available_copies integer not null default 1 check (available_copies >= 0),
  search_vector tsvector,
  created_at timestamptz not null default now(),
  check (available_copies <= total_copies)
);

create table if not exists public.borrow_requests (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'returned')),
  request_date timestamptz not null default now(),
  due_date timestamptz,
  returned_date timestamptz,
  duration_days integer not null default 14 check (duration_days between 7 and 90),
  renewal_count integer not null default 0 check (renewal_count >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique (book_id, student_id)
);

create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (book_id, student_id)
);

create table if not exists public.study_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  page integer,
  text text,
  selection_text text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.highlights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  page integer not null,
  rects jsonb not null,
  color text not null default 'yellow',
  note_id bigint references public.study_notes(id) on delete set null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.fines (
  id bigint generated by default as identity primary key,
  borrow_request_id bigint not null unique references public.borrow_requests(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(10, 2) not null default 0 check (amount >= 0),
  status text not null default 'unpaid' check (status in ('unpaid', 'paid')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.email_queue (
  id bigint generated by default as identity primary key,
  event_type text not null,
  payload jsonb not null,
  processed boolean not null default false,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.assistant_sessions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'New research chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assistant_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.assistant_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  results jsonb not null default '[]'::jsonb,
  loans jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_books_title_trgm on public.books using gin (title gin_trgm_ops);
create index if not exists idx_books_search_vector on public.books using gin (search_vector);
create index if not exists idx_borrow_requests_student_status on public.borrow_requests(student_id, status, due_date);
create index if not exists idx_borrow_requests_book_status on public.borrow_requests(book_id, status);
create index if not exists idx_books_category on public.books(category);
create index if not exists idx_study_notes_user_book on public.study_notes(user_id, book_id, page);
create index if not exists idx_highlights_user_book on public.highlights(user_id, book_id, page);
create index if not exists idx_fines_student on public.fines(student_id);
create index if not exists idx_email_queue_event_type on public.email_queue(event_type);
create index if not exists idx_assistant_sessions_user on public.assistant_sessions(user_id, updated_at desc);
create index if not exists idx_assistant_messages_session on public.assistant_messages(session_id, created_at);

create or replace function public.sync_book_search_vector()
returns trigger
language plpgsql
as $$
begin
  new.search_vector := to_tsvector(
    'english',
    coalesce(new.title, '') || ' ' ||
    coalesce(new.author, '') || ' ' ||
    coalesce(new.description, '') || ' ' ||
    coalesce(new.category, '')
  );
  return new;
end;
$$;

drop trigger if exists trg_books_search_vector on public.books;
create trigger trg_books_search_vector
before insert or update on public.books
for each row execute function public.sync_book_search_vector();

update public.books
set search_vector = to_tsvector(
  'english',
  coalesce(title, '') || ' ' || coalesce(author, '') || ' ' ||
  coalesce(description, '') || ' ' || coalesce(category, '')
)
where search_vector is null;

create or replace function public.search_books(p_query text, p_limit integer default 10)
returns table(
  id bigint,
  title text,
  author text,
  category text,
  description text,
  pdf_url text,
  available_copies integer,
  rank double precision
)
language sql
stable
security invoker
as $$
  select b.id, b.title, b.author, b.category, b.description, b.pdf_url,
         b.available_copies,
         ts_rank(b.search_vector, plainto_tsquery('english', p_query)) as rank
  from public.books b
  where b.search_vector @@ plainto_tsquery('english', p_query)
  order by rank desc
  limit least(greatest(coalesce(p_limit, 10), 1), 50);
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_study_notes_updated_at on public.study_notes;
create trigger trg_study_notes_updated_at
before update on public.study_notes
for each row execute function public.touch_updated_at();

create or replace function public.enqueue_borrow_request_notifications()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from new.status and new.status in ('approved', 'rejected') then
    insert into public.email_queue(event_type, payload)
    values ('borrow_request_status', jsonb_build_object(
      'student_id', new.student_id,
      'book_id', new.book_id,
      'status', new.status,
      'request_id', new.id
    ));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enqueue_borrow_request_notifications on public.borrow_requests;
create trigger trg_enqueue_borrow_request_notifications
after update on public.borrow_requests
for each row execute function public.enqueue_borrow_request_notifications();

create or replace function public.calculate_overdue_fines(daily_rate numeric default 0.5)
returns void language plpgsql security definer set search_path = public as $$
declare
  loan record;
  days_overdue integer;
begin
  for loan in
    select id, student_id, due_date
    from public.borrow_requests
    where status = 'approved' and due_date is not null
      and (returned_date is null or returned_date > due_date)
  loop
    days_overdue := greatest(0, date_part('day', now()::date - loan.due_date::date)::integer);
    if days_overdue > 0 then
      insert into public.fines(borrow_request_id, student_id, amount)
      values (loan.id, loan.student_id, days_overdue * daily_rate)
      on conflict (borrow_request_id) do update
      set amount = excluded.amount, status = 'unpaid', created_at = now();
    end if;
  end loop;
end;
$$;

create or replace function public.request_digital_loan(p_book_id bigint, p_duration_days integer)
returns public.borrow_requests language plpgsql security definer set search_path = public as $$
declare
  requested public.borrow_requests;
  active_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_duration_days < 7 or p_duration_days > 90 then
    raise exception 'Choose a lending period between 7 and 90 days';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text || ':' || p_book_id::text, 0));
  if not exists (select 1 from public.books where id = p_book_id) then
    raise exception 'Resource not found';
  end if;

  select count(*) into active_count
  from public.borrow_requests
  where student_id = auth.uid() and status = 'approved'
    and returned_date is null and due_date > now();
  if active_count >= 3 then
    raise exception 'You have reached the maximum of 3 active digital loans';
  end if;

  if exists (
    select 1 from public.borrow_requests
    where student_id = auth.uid() and book_id = p_book_id
      and (status = 'pending' or (status = 'approved' and returned_date is null and due_date > now()))
  ) then
    raise exception 'You already have an active request or loan for this resource';
  end if;

  insert into public.borrow_requests(student_id, book_id, duration_days)
  values (auth.uid(), p_book_id, p_duration_days)
  returning * into requested;
  return requested;
end;
$$;

create or replace function public.provision_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'student')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.provision_profile();

-- Backfill accounts created before this schema was installed.
insert into public.profiles (id, email, role)
select id, coalesce(email, ''), 'student'
from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.prevent_student_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.role is distinct from new.role
     and auth.uid() is not null
     and not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    raise exception 'Only an administrator can change account roles';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_role_guard on public.profiles;
create trigger trg_profiles_role_guard
before update on public.profiles
for each row execute function public.prevent_student_role_change();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.admin_set_profile_role(target_user_id uuid, new_role text)
returns public.profiles language plpgsql security definer set search_path = public as $$
declare
  updated_profile public.profiles;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  if new_role not in ('student', 'admin') then raise exception 'Invalid account role'; end if;
  update public.profiles set role = new_role where id = target_user_id returning * into updated_profile;
  if updated_profile.id is null then raise exception 'Profile not found'; end if;
  return updated_profile;
end;
$$;

create or replace function public.admin_decide_borrow_request(request_id bigint, decision text)
returns public.borrow_requests language plpgsql security definer set search_path = public as $$
declare
  updated_request public.borrow_requests;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  if decision not in ('approved', 'rejected') then raise exception 'Invalid request decision'; end if;
  update public.borrow_requests
  set status = decision,
      due_date = case when decision = 'approved' then now() + make_interval(days => duration_days) else null end
  where id = request_id and status = 'pending'
  returning * into updated_request;
  if updated_request.id is null then raise exception 'Pending request not found'; end if;
  return updated_request;
end;
$$;

create or replace function public.renew_digital_loan(request_id bigint, extension_days integer default 14)
returns public.borrow_requests language plpgsql security definer set search_path = public as $$
declare
  updated_request public.borrow_requests;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if extension_days < 7 or extension_days > 30 then raise exception 'Renewal must be between 7 and 30 days'; end if;
  update public.borrow_requests
  set due_date = greatest(coalesce(due_date, now()), now()) + make_interval(days => extension_days),
      renewal_count = renewal_count + 1
  where id = request_id and student_id = auth.uid() and status = 'approved'
    and returned_date is null and due_date > now() and renewal_count < 2
  returning * into updated_request;
  if updated_request.id is null then raise exception 'Loan cannot be renewed'; end if;
  return updated_request;
end;
$$;

create or replace function public.return_digital_loan(request_id bigint)
returns public.borrow_requests language plpgsql security definer set search_path = public as $$
declare
  updated_request public.borrow_requests;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.borrow_requests
  set status = 'returned', returned_date = now()
  where id = request_id and student_id = auth.uid() and status = 'approved' and returned_date is null
  returning * into updated_request;
  if updated_request.id is null then raise exception 'Loan cannot be returned'; end if;
  return updated_request;
end;
$$;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.borrow_requests enable row level security;
alter table public.reviews enable row level security;
alter table public.wishlists enable row level security;
alter table public.study_notes enable row level security;
alter table public.highlights enable row level security;
alter table public.fines enable row level security;
alter table public.email_queue enable row level security;
alter table public.assistant_sessions enable row level security;
alter table public.assistant_messages enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles
for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles
for insert to authenticated
with check (id = auth.uid() and role = 'student');

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists books_read_authenticated on public.books;
create policy books_read_authenticated on public.books
for select to authenticated using (true);

drop policy if exists books_admin_insert on public.books;
create policy books_admin_insert on public.books
for insert to authenticated with check (public.is_admin());

drop policy if exists books_admin_update on public.books;
create policy books_admin_update on public.books
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists books_admin_delete on public.books;
create policy books_admin_delete on public.books
for delete to authenticated using (public.is_admin());

drop policy if exists borrow_requests_read_owner_or_admin on public.borrow_requests;
create policy borrow_requests_read_owner_or_admin on public.borrow_requests
for select to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists borrow_requests_admin_update on public.borrow_requests;
create policy borrow_requests_admin_update on public.borrow_requests
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists reviews_read_authenticated on public.reviews;
create policy reviews_read_authenticated on public.reviews
for select to authenticated using (true);

drop policy if exists reviews_insert_own on public.reviews;
create policy reviews_insert_own on public.reviews
for insert to authenticated with check (student_id = auth.uid());

drop policy if exists reviews_update_own_or_admin on public.reviews;
create policy reviews_update_own_or_admin on public.reviews
for update to authenticated
using (student_id = auth.uid() or public.is_admin())
with check (student_id = auth.uid() or public.is_admin());

drop policy if exists reviews_delete_own_or_admin on public.reviews;
create policy reviews_delete_own_or_admin on public.reviews
for delete to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists wishlists_manage_own_or_admin on public.wishlists;
create policy wishlists_manage_own_or_admin on public.wishlists
for all to authenticated
using (student_id = auth.uid() or public.is_admin())
with check (student_id = auth.uid() or public.is_admin());

drop policy if exists study_notes_manage_own_or_admin on public.study_notes;
create policy study_notes_manage_own_or_admin on public.study_notes
for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists highlights_manage_own_or_admin on public.highlights;
create policy highlights_manage_own_or_admin on public.highlights
for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists fines_read_own_or_admin on public.fines;
create policy fines_read_own_or_admin on public.fines
for select to authenticated using (student_id = auth.uid() or public.is_admin());

drop policy if exists fines_admin_update on public.fines;
create policy fines_admin_update on public.fines
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists assistant_sessions_manage_own on public.assistant_sessions;
create policy assistant_sessions_manage_own on public.assistant_sessions
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists assistant_messages_manage_own on public.assistant_messages;
create policy assistant_messages_manage_own on public.assistant_messages
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select, insert, update, delete on public.books to authenticated;
grant select, update on public.borrow_requests to authenticated;
grant select, insert, update, delete on public.reviews to authenticated;
grant select, insert, update, delete on public.wishlists to authenticated;
grant select, insert, update, delete on public.study_notes to authenticated;
grant select, insert, update, delete on public.highlights to authenticated;
grant select, update on public.fines to authenticated;
grant select, insert, update, delete on public.assistant_sessions to authenticated;
grant select, insert, update, delete on public.assistant_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.search_books(text, integer) to authenticated;
grant execute on function public.request_digital_loan(bigint, integer) to authenticated;
grant execute on function public.admin_set_profile_role(uuid, text) to authenticated;
grant execute on function public.admin_decide_borrow_request(bigint, text) to authenticated;
grant execute on function public.renew_digital_loan(bigint, integer) to authenticated;
grant execute on function public.return_digital_loan(bigint) to authenticated;

-- Do not grant direct student inserts. Student requests must use the validated RPC.
revoke insert on public.borrow_requests from anon, authenticated;

revoke all on public.email_queue from anon, authenticated;
revoke all on function public.calculate_overdue_fines(numeric) from public;

-- After creating your first account, promote it manually from the SQL editor:
-- update public.profiles set role = 'admin' where email = 'your-admin-email@example.com';
