-- Migration: add e-reader support, reviews, wishlists, email queue, fines

-- 1) Add pdf_url to books (your schema uses `pdf_url`)
ALTER TABLE IF EXISTS public.books
  ADD COLUMN IF NOT EXISTS pdf_url text;

-- 2) Reviews table (one review per student per book)
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id bigint REFERENCES public.books(id) ON DELETE CASCADE NOT NULL,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  rating int CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  comment text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(book_id, student_id)
);

-- 3) Wishlist table
CREATE TABLE IF NOT EXISTS public.wishlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id bigint REFERENCES public.books(id) ON DELETE CASCADE NOT NULL,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(book_id, student_id)
);

-- 4) Enable RLS on reviews and wishlists and add policies
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Reviews policies (owners or admins)
-- Helper expression: owner or admin
CREATE POLICY "Anyone can read reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Students can post reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Review owners or admins can update reviews" ON public.reviews FOR UPDATE USING (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
) WITH CHECK (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);
CREATE POLICY "Review owners or admins can delete reviews" ON public.reviews FOR DELETE USING (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- Wishlist policies (owners or admins)
CREATE POLICY "Users can manage their wishlist" ON public.wishlists FOR ALL USING (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
) WITH CHECK (
  auth.uid() = student_id OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- 5) Fines
CREATE TABLE IF NOT EXISTS public.fines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  borrow_request_id bigint REFERENCES public.borrow_requests(id) ON DELETE CASCADE NOT NULL,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount numeric(10,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid','paid')),
  created_at timestamptz DEFAULT timezone('utc'::text, now()),
  paid_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_fines_student ON public.fines(student_id);

-- 6) Email queue for async notifications (consumed by an Edge Function or background worker)
CREATE TABLE IF NOT EXISTS public.email_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT timezone('utc'::text, now()),
  processed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_email_queue_event_type ON public.email_queue(event_type);

-- 7) Trigger: enqueue notifications when borrow_requests status changes
CREATE OR REPLACE FUNCTION public.enqueue_borrow_request_notifications()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
      IF NEW.status IN ('approved', 'rejected') THEN
        INSERT INTO public.email_queue(event_type, payload)
        VALUES (
          'borrow_request_status',
          jsonb_build_object(
            'student_id', NEW.student_id,
            'book_id', NEW.book_id,
            'status', NEW.status,
            'request_id', NEW.id
          )
        );
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_enqueue_borrow_request_notifications ON public.borrow_requests;
CREATE TRIGGER trg_enqueue_borrow_request_notifications
AFTER UPDATE ON public.borrow_requests
FOR EACH ROW
EXECUTE FUNCTION public.enqueue_borrow_request_notifications();

-- 8) Helper function to calculate fines (call from a scheduled job)
CREATE OR REPLACE FUNCTION public.calculate_overdue_fines(daily_rate numeric DEFAULT 0.5)
RETURNS void AS $$
DECLARE
  br RECORD;
  days_overdue integer;
  fine_amount numeric;
BEGIN
  FOR br IN
    SELECT id, student_id, due_date
    FROM public.borrow_requests
    WHERE status = 'approved' AND due_date IS NOT NULL AND (returned_date IS NULL OR returned_date > due_date)
  LOOP
    days_overdue := GREATEST(0, DATE_PART('day', now()::date - br.due_date::date));
    IF days_overdue > 0 THEN
      fine_amount := days_overdue * daily_rate;
      -- upsert a fine linked to this borrow_request
      INSERT INTO public.fines(borrow_request_id, student_id, amount)
      VALUES (br.id, br.student_id, fine_amount)
      ON CONFLICT (borrow_request_id) DO UPDATE SET amount = EXCLUDED.amount, status = 'unpaid', created_at = timezone('utc'::text, now());
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Notes:
-- - Use Supabase Edge Function or external worker to poll `public.email_queue` and send emails (Resend/SendGrid).
-- - Schedule `public.calculate_overdue_fines()` via pg_cron or an external scheduler to run daily.
